-- ===========================================================================
--  Umstieg auf Supabase Auth
-- ===========================================================================
--
--  Die App nutzt jetzt Supabase Auth (Login/Registrierung/E-Mail-Bestätigung/
--  Google/GitHub). Das Backend prüft nur noch Supabase-Tokens und speichert die
--  Daten pro Supabase-User-UUID in der Tabelle "mt_user_data".
--
--  Diese Tabelle legt Hibernate (ddl-auto=update) beim Start AUTOMATISCH an —
--  hier ist also normalerweise NICHTS zu tun.
--
--  Optional: die alten, nicht mehr genutzten Tabellen der früheren Eigen-Auth
--  aufräumen. Vorher sicher sein, dass keine wichtigen Daten mehr drinstecken
--  (die App-Daten lagen ohnehin lokal im Browser und werden nach dem Login neu
--  in mt_user_data hochgeladen).
--
--  In Supabase ausführen:  SQL Editor → einfügen → Run.

-- DROP TABLE IF EXISTS mt_email_tokens;
-- DROP TABLE IF EXISTS mt_app_data;
-- DROP TABLE IF EXISTS mt_users;
